### ISSUE TITLE
VM booting takes too long?

### ISSUE THREAD

**Issue by ymnliu** [nlpie/nlp-adapt#13]
This is Sijia from Mayo. With a limit of 3GB memory to the VM, the booting stops at black screen after I select "Ubuntu". Do you have the same issue?

**Comment by ymnliu** [comment]
Resolved after switching to a different host OS

**Comment by rfinz** [comment]
Hi @ymnliu what was the host OS that you were having trouble with? Our goal is for the VM to be completely portable.

**Comment by ymnliu** [comment]
Hi @rfinz, I first tested it on an 8GB RAM Windows 7, without CPU acceleration (VT-x). But now on OS X the VM can boot even with 3GB RAM. Thus, the RAM size should not be the bottleneck. My guess is the VT-x option the performance booster, but I am not 100% sure about this.
