### ISSUE TITLE
Documentation Enhancements

### ISSUE THREAD

**Issue by rfinz** [nlpie/nlp-adapt#16]
Known Issues:
- [x] unspecified behavior with shared filesystem and docker on MacOSX
- [x] powering off system between annotator runs results in unknown state

NLP-TAB:
- [x] Instructions needed to manually upload xmi and typesystem

AMICUS:
- [x] Explanation needed for how/when to manually edit the configuration file, since the default configuration fails when not all annotation engines are run, for example.

**Comment by GregSilverman** [comment]
File locking issue will only fail annotation if the file has a known issue that was detected during linting and the file persists even after deletion from host's shared directory. Not sure how to word this in the documentation, other than as "strange behavior."

**Comment by rfinz** [comment]
Yeah, I think just making it clear that the shared filesystem can cause problems if you're not careful should be fine. I wouldn't even mention what you just said - better to just indicate that caution should be used when browsing the shared filesystem.

**Comment by GregSilverman** [comment]
We should also add a comment about keeping the packages on the VM up-to-date.

**Comment by GregSilverman** [comment]
@rfinz, I finally figured out what was making MetaMap have a conniption. If the file .DS_Store is in the host directory, then all bets are off. We'll need to add this to the directions. It took me 2.5 hours to figure this one out. Oy!

**Comment by rfinz** [comment]
basic documentation enhancements included - should be fleshed out when we migrate to a wiki
