### ISSUE TITLE
Verify Initial VM Extension

### ISSUE THREAD

**Issue by rmcewan** [nlpie/nlp-adapt#3]
Perform a verification similar to that in #1, using the changes to the VM outlined in #2 

- [x] ctakes (1.5+ hour run time with 1 cpu and 4 gigs of RAM on 10K files)
- [x] metamap
- [x] metamap-uima
- [x] amicus with all three outputs
- [x] nlp-tab integration

~~clamp(?)~~

- [x] whole pipeline

**Comment by rfinz** [comment]
I think we should consider this complete. Any other tasks for the initial extension are bugs or enhancements.
