### ISSUE TITLE
Initial Documentation

### ISSUE THREAD

**Issue by rmcewan** [nlpie/nlp-adapt#5]
- [x] initial setup procedure
- [x] running the pipeline
  - [x] annotators
  - [x] nlp-tab
  - [x] amicus
- [x] known issues
- [x] enhancements
- [x] upload markup file into this repo (wiki?)

**Comment by rmcewan** [comment]
Depends on #3

**Comment by rfinz** [comment]
Hopefully testing this with @GregSilverman next week tuesday - but certain pipeline components may not be fully functional.

**Comment by rfinz** [comment]
Documentation is being edited [here](https://docs.google.com/document/d/1-mDPBDrB78Q6dYjQgadWHKRbT9649yi7lrVi2HDe_oE) after initial evaluation from @GregSilverman .

**Comment by rfinz** [comment]
I'm going to close this issue in favor of #14 and #16
